# Generated by Django 5.2.7 on 2025-10-29 21:03

import jt.apps.attribute.enums
import jt.apps.common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subsystemattribute",
            name="attribute_type_str",
        ),
        migrations.RemoveField(
            model_name="subsystemattribute",
            name="value_type_str",
        ),
        migrations.AddField(
            model_name="subsystemattribute",
            name="attribute_type",
            field=jt.apps.common.model_fields.LabeledEnumField(
                choices=[("predefined", "Predefined"), ("custom", "Custom")],
                default="predefined",
                enum_class=jt.apps.attribute.enums.AttributeType,
                max_length=32,
                use_safe_conversion=True,
                verbose_name="Attribute Type",
            ),
        ),
        migrations.AddField(
            model_name="subsystemattribute",
            name="value_type",
            field=jt.apps.common.model_fields.LabeledEnumField(
                choices=[
                    ("text", "Text"),
                    ("file", "File"),
                    ("secret", "Secret"),
                    ("enum", "Enum"),
                    ("boolean", "Boolean"),
                    ("integer", "Integer"),
                    ("float", "Float"),
                ],
                default="text",
                enum_class=jt.apps.attribute.enums.AttributeValueType,
                max_length=32,
                use_safe_conversion=True,
                verbose_name="Value Type",
            ),
        ),
    ]
